export const styles = {
    socialNetRoot: "p-4 flex-1",
    titleContainer: "py-4",
    titleText: "text-4xl font-extrabold text-[#5CB868]",
    createPostContainer: "flex flex-row items-center rounded-full gap-2",
    profileImageThumbnail: "object-cover h-11 w-11 rounded-full",
    postContentInput: "flex-1 px-3 py-3 rounded-[20] font-semibold text-xl bg-[#F3F4F6]",
    postImageThumbnail: "w-11 h-11 rounded-lg",
    modalWidth: "w-3/4",
    modalHeight: "h-[41%]",
    modalImage: "w-full aspect-square rounded-lg",
    chooseImageButton: "flex-row gap-2 items-center mt-4 px-4 py-2 bg-[#A5D6A7] rounded-lg",
    chooseImageButtonText: "text-[#142C15] font-bold",
    noImageText: "text-gray-500",
    publishButtonContainer: "my-3",
    publishButton: "bg-[#5CB868] py-3 px-4 rounded-[20px]",
    publishButtonText: "text-[#fff] text-center text-xl font-medium",
    sortButtonsContainer: "flex flex-row justify-start gap-2 mb-4",
    formContainer: "w-full bg-white rounded-xl relative ${ width > 400 ? \"max-w-[25rem]\" : \"max-w-[calc(100%-40px)]\"}",
    inputFirstName: "h-14 px-4 mb-3 rounded-xl text-lg bg-[#F3F4F6] w-[48%] ${ firstName ? \"text-black\" : \"text-[#9CA3AF]\"}",
    inputLastName: "h-14 px-4 mb-3 rounded-xl text-lg bg-[#F3F4F6] w-[48%] ${ lastName ? \"text-black\" : \"text-[#9CA3AF]\"}",
    birthDateLabel: "text-base text-black mb-2 font-bold",
    birthDateContainer: "flex-row justify-between mb-3",
    genderLabel: "text-base text-black mb-2 font-bold",
    pronounLabel: "text-base text-black mb-2 font-bold",
    pronounDescription: "text-xs text-[#666] mb-3",
    customGenderLabel: "text-base text-black mb-2 font-bold",
    inputCustomGender: "h-14 px-4 mb-3 rounded-xl text-lg bg-[#F3F4F6] w-full ${ customGender ? \"text-black\" : \"text-[#9CA3AF]\"}",
    inputEmail: "h-14 px-4 mb-3 rounded-xl text-lg bg-[#F3F4F6] w-full ${ email ? \"text-black\" : \"text-[#9CA3AF]\"}",
    passwordContainer: "relative",
    inputPassword: "h-14 px-4 mb-3 rounded-xl text-lg bg-[#F3F4F6] w-full ${ password ? \"text-black\" : \"text-[#9CA3AF]\"}",
    passwordToggleContainer: "absolute z-20 right-4 top-3",
    headerImage: "w-3/5 aspect-square self-center mb-[-40px]",
    headerTitle: "font-bold text-2xl text-center mb-5",
    termsText: "text-base text-black",
    termsLink: "text-[#5CB868]",
    registerButton: "items-center my-3 p-4 rounded-xl bg-[#5CB868]",
    registerButtonText: "text-white font-bold text-lg",
    loginLinkContainer: "text-black text-center mt-3 text-base",
    loginLinkText: "text-black",
    loginLinkHighlight: "text-[#5CB868]",
    postItemRoot: "bg-[#F3F4F6] mb-2 rounded-lg flex gap-3",
    postHeaderContainer: "flex flex-row items-center gap-2 px-4 pt-4",
    postUserProfileImage: "object-cover h-8 w-8 rounded-full",
    postUsernameText: "color-[#5CB868] font-bold text-xl",
    postContentText: "text-xl px-4 py-2",
    postImageContainer: "w-auto aspect-square rounded-lg mx-2 object-cover",
    postActionsContainer: "flex flex-row items-center justify-start gap-2 px-4 pt-3 pb-2",
    likeButton: "flex flex-row items-center gap-2 w-12",
    commentButton: "flex flex-row items-center gap-2 w-12",
    postTimeText: "text-[#565a63] px-4 pb-4",
    commentsContainer: "flex gap-4 pb-4 px-5",
    commentContainer: "flex flex-row items-center gap-2",
    commentUserProfileImage: "object-cover h-8 w-8 rounded-full",
    commentTextContainer: "flex",
    commentInputContainer: "flex flex-row gap-2 items-center",
    commentInput: "flex-1 px-4 rounded-full text-xl bg-white",
    commentSendIcon: "w-7",
    modalPostImage: "w-full aspect-square rounded-lg",
    modalProfileImage: "w-full aspect-square rounded-lg",
  };
  